import { useRef, useState, useCallback } from 'react';
import {
  UploadCloud,
  ScanEye,
  Zap,
  FileImage,
  ArrowRight,
} from 'lucide-react';

const HERO_ARTWORK =
  'https://images.pexels.com/photos/1546249/pexels-photo-1546249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';

const STATS = [
  { value: '91.7%', label: 'Test Accuracy', icon: ScanEye },
  { value: 'Fast', label: 'Analysis', icon: Zap },
  { value: 'Multi', label: 'Image Formats', icon: FileImage },
];

interface HeroProps {
  onFileSelect: (file: File) => void;
}

export default function Hero({ onFileSelect }: HeroProps) {
  const [dragOver, setDragOver] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setDragOver(false);
      const file = e.dataTransfer.files?.[0];
      if (file && file.type.startsWith('image/')) {
        onFileSelect(file);
      }
    },
    [onFileSelect],
  );

  const handleBrowse = () => inputRef.current?.click();

  return (
    <section id="hero" className="relative overflow-hidden pt-24 pb-16 lg:pt-32 lg:pb-24">
      {/* Background */}
      <div className="absolute inset-0 grid-pattern opacity-40" />
      <div className="absolute inset-0 bg-gradient-to-b from-ink-950 via-transparent to-ink-950" />
      <div className="absolute -top-40 right-0 h-[500px] w-[500px] rounded-full bg-teal-500/10 blur-[120px]" />
      <div className="absolute top-1/2 left-0 h-[400px] w-[400px] rounded-full bg-teal-600/8 blur-[100px]" />

      <div className="relative mx-auto max-w-7xl px-5 lg:px-8">
        <div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-16">
          {/* Left: content */}
          <div className="animate-fade-up">
            <div className="inline-flex items-center gap-2 rounded-full border border-teal-500/30 bg-teal-500/10 px-4 py-1.5 mb-6">
              <span className="relative flex h-2 w-2">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-teal-400 opacity-75" />
                <span className="relative inline-flex h-2 w-2 rounded-full bg-teal-400" />
              </span>
              <span className="font-mono text-xs font-medium text-teal-300">
                CNN Model · 3.3M Parameters · Online
              </span>
            </div>

            <h1 className="font-display text-4xl font-bold leading-[1.1] tracking-tight text-ink-50 sm:text-5xl lg:text-6xl">
              Is This Artwork
              <br />
              <span className="text-gradient">AI-Generated?</span>
            </h1>

            <p className="mt-6 max-w-lg text-base leading-relaxed text-ink-300 sm:text-lg">
              Upload any artwork and our trained convolutional neural network will
              determine whether it was created by a human artist or generated by AI.
              Real analysis, real confidence — powered by a custom CNN model.
            </p>

            {/* Stats */}
            <div className="mt-8 flex flex-wrap gap-3">
              {STATS.map((stat) => (
                <div
                  key={stat.label}
                  className="glass flex items-center gap-2.5 rounded-xl px-4 py-3 transition-transform hover:scale-105"
                >
                  <stat.icon className="h-4 w-4 text-teal-400" />
                  <div className="flex flex-col leading-none">
                    <span className="font-display text-lg font-bold text-ink-50">
                      {stat.value}
                    </span>
                    <span className="text-xs text-ink-400">{stat.label}</span>
                  </div>
                </div>
              ))}
            </div>

            {/* Upload button */}
            <div className="mt-8 flex flex-wrap items-center gap-4">
              <button
                onClick={handleBrowse}
                className="group inline-flex items-center gap-2.5 rounded-xl bg-gradient-to-br from-teal-400 to-teal-600 px-6 py-3.5 text-sm font-semibold text-ink-950 transition-all hover:from-teal-300 hover:to-teal-500 hover:glow-teal-sm active:scale-95"
              >
                <UploadCloud className="h-5 w-5" strokeWidth={2.5} />
                Upload an Image
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
              </button>
              <a
                href="#how-it-works"
                className="text-sm font-medium text-ink-300 transition-colors hover:text-teal-400"
              >
                How it works →
              </a>
            </div>

            <input
              ref={inputRef}
              type="file"
              accept="image/png,image/jpeg,image/jpg,image/webp,image/bmp"
              className="hidden"
              onChange={(e) => {
                const file = e.target.files?.[0];
                if (file) onFileSelect(file);
                e.target.value = '';
              }}
            />
          </div>

          {/* Right: visual */}
          <div className="relative animate-fade-up animation-delay-200" style={{ animationDelay: '0.15s' }}>
            {/* Drag-drop area */}
            <div
              onDragOver={(e) => {
                e.preventDefault();
                setDragOver(true);
              }}
              onDragLeave={() => setDragOver(false)}
              onDrop={handleDrop}
              onClick={handleBrowse}
              className={`group relative cursor-pointer overflow-hidden rounded-3xl border-2 transition-all duration-300 ${
                dragOver
                  ? 'border-teal-400 glow-teal scale-[1.02]'
                  : 'border-ink-700 hover:border-teal-500/50'
              }`}
            >
              <div className="relative aspect-[4/3] overflow-hidden rounded-3xl">
                <img
                  src={HERO_ARTWORK}
                  alt="Abstract artwork for AI detection"
                  className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-ink-950 via-ink-950/30 to-transparent" />

                {/* Scan overlay */}
                <div className="pointer-events-none absolute inset-0 overflow-hidden">
                  <div className="absolute inset-x-0 h-px bg-gradient-to-r from-transparent via-teal-400 to-transparent opacity-70" style={{ top: '50%', boxShadow: '0 0 20px rgba(52,211,166,0.8)', animation: 'scanLine 3s ease-in-out infinite' }} />
                </div>

                {/* Drag-drop prompt */}
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-ink-950/40 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                  <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-teal-500/20 backdrop-blur-sm border border-teal-400/30">
                    <UploadCloud className="h-8 w-8 text-teal-300" />
                  </div>
                  <p className="font-display text-lg font-semibold text-ink-50">
                    Drop image to analyze
                  </p>
                  <p className="text-xs text-ink-300">or click to browse</p>
                </div>

                {/* Corner brackets */}
                <div className="absolute left-4 top-4 h-6 w-6 border-l-2 border-t-2 border-teal-400/60 rounded-tl-lg" />
                <div className="absolute right-4 top-4 h-6 w-6 border-r-2 border-t-2 border-teal-400/60 rounded-tr-lg" />
                <div className="absolute bottom-4 left-4 h-6 w-6 border-l-2 border-b-2 border-teal-400/60 rounded-bl-lg" />
                <div className="absolute bottom-4 right-4 h-6 w-6 border-r-2 border-b-2 border-teal-400/60 rounded-br-lg" />
              </div>
            </div>

            {/* Floating info card */}
            <div className="absolute -bottom-5 -left-5 glass rounded-2xl px-5 py-3.5 shadow-xl shadow-black/40 hidden sm:block">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-teal-500/20">
                  <ScanEye className="h-5 w-5 text-teal-400" />
                </div>
                <div>
                  <p className="font-mono text-xs text-ink-400">Analysis Engine</p>
                  <p className="font-display text-sm font-semibold text-ink-50">
                    CNN · 128×128 Input
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <style>{`
        @keyframes scanLine {
          0%, 100% { top: 10%; }
          50% { top: 90%; }
        }
      `}</style>
    </section>
  );
}
